apiVersion: v1
kind: Pod
metadata:
  name: busy-from-snap
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do sleep 1; done"
    volumeMounts:
    - name: volume
      mountPath: /tmp
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: snapshot-pv-provisioning-demo
